# Generated by Django 3.2 on 2021-04-29 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boysapp', '0004_auto_20210428_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated',
            new_name='created_on',
        ),
    ]
